badge-server-url: http://badges.falsifiable.us
metadata:
  access_right: open
  license: CC-BY-4.0
  publication_type: article
  upload_type: publication
pipelines:
  cloudlab-multisite-transfer:
    envs:
      host:
        args: []
    parameters: []
    path: pipelines/cloudlab-multisite-transfer
    requirements: {}
    stages:
    - setup
search_sources:
- popperized
version: 1
